Downgrade Node.js to fix builds on Travis CI
danrabbit/harvey pull request #35
Opened 2019-11-08 19:51 UTC by meisenzahl

2019-11-15 08:50 UTC, NathanBnm approved these changes

2020-05-01 12:19 UTC, NathanBnm requested changes

2020-05-01 12:19 UTC, NathanBnm commented on .travis.yml
> +  - 10/*
```suggestion
  - 10.17.0
```

2020-10-25 07:44 UTC, NathanBnm approved these changes

2020-10-26 23:12 UTC, danrabbit commented
Thanks for submitting this, but I'm actually going to switch to using Flatpak for CI from now on!

2020-10-26 23:12 UTC, closed without merging